/*RELACIONAMENTO DE TABELAS*/

CREATE TABLE IF NOT EXISTS VENDAS(
ID INT PRIMARY KEY AUTO_INCREMENT, DATA_VENDA DATE NOT NULL, CLIENTEID INT NOT NULL, 
TOTAL_VENDAS FLOAT NOT NULL, 
FOREIGN KEY(CLIENTEID) REFERENCES CLIENTES(ID) /*EXISTE UMA CHAVE ESTRANGEIRA CHAMADA CLIENTEID, QUE FAZ REFERENCIA A TABELA DE CLIENTES EXPECIFICAMENTENA COLUNA ID*/
);


/*UTILIZANDO CHAVE PRIMARIA COMPOSTA*/

MariaDB [BANCOTREINAMENTO]> CREATE TABLE IF NOT EXISTS ITENS_VENDAS(IDPRODUTO INT NOT NULL, IDVENDA INT NOT NULL,VALORPRODUTO INT NOT NULL,DESCONTO INT NOT NULL,FOREIGN KEY(IDVENDA) REFERENCES VENDAS(ID),FOREIGN KEY(IDPRODUTO) REFERENCES PRODUTOS(ID_PRODUTOS), PRIMARY KEY(IDPRODUTO,IDVENDA)

/*PRIMARY KEY(IDPRODUTO,IDVENDA)) - CHAVE PRIMERIA COMPOSTA*/
);

/*INSERINDO VALORES NA TABELA PRODUTOS*/
MariaDB [BANCOTREINAMENTO]> INSERT INTO PRODUTOS VALUES(DEFAULT,'MANTEIGA',40.50,1);

/*INSERINDO VALORES NA TABELA VENDAS*/
INSERT INTO VENDAS VALUES(DEFAULT,'2023-07-19',1,999);

/*INSERINDO VALORES NA TABELA ITENS_VENDAS*/
MariaDB [BANCOTREINAMENTO]> INSERT INTO ITENS_VENDAS VALUES(1,1,50,0);

