
CREATE TABLE IF NOT EXISTS CATEGORIAS(ID_CATEGORIAS INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(30) NOT NULL);

/*CRIANDO UM TABELA QU VA ISE RELACIONAR COM A TABELA CATEGORIA*/

CREATE TABLE IF NOT EXISTS PRODUTOS( ID_PRODUTOS INT PRIMARY KEY AUTO_INCREMENT,
  DESCRICAO TEXT NOT NULL,PRECO FLOAT NOT NULL,
  CATEGORIA_ID INT NOT NULL, FOREIGN KEY(CATEGORIA_ID) REFERENCES CATEGORIAS(ID_CATEGORIAS));
