/*APAGANDO A TABELA*/
DROP TABLE CLIENTES;

/*CRIANDO UMA NOVA TABELA*/

MariaDB [BANCOTREINAMENTO]> CREATE TABLE IF NOT EXISTS USUARIOS(ID INT PRIMARY KEY AUTO_INCREMENT,NOME VARCHAR(30) NOT NULL UNIQUE,CPF CHAR(11) NOT NULL,DATA_NASCIMENTO DATE NOT NULL, SEXO ENUM('M','F') NOT NULL,EMAIL VARCHAR(70) NOT NULL,ATIVO BIT NOT NULL);

/*ISERINDO DADOS NA NOVA TABELA*/

MariaDB [BANCOTREINAMENTO]> INSERT INTO USUARIOS VALUES(DEFAULT,'RAFAELA RAFA','12345678911','1990-01-01','M','rafaelarafa@sgbd.com',FALSE);

MariaDB [BANCOTREINAMENTO]> INSERT INTO USUARIOS VALUES(
DEFAULT,'BIANCA FLORES','25896374100','1980-08-15','F','biancoflor@sgbd.com',TRUE),(DEFAULT,'CARLOS CALOURO','0000000098','1975-06-23','M','carlosc@sgbd.com.br',TRUE),(DEFAULT,'MARCIOPEREIRA','77886655312','2001-12-25','M','marciosantos@sgbd.com',FALSE);

