
CREATE TABLE IF NOT EXISTS CATEGORIAS(ID_CATEGORIAS INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(30) NOT NULL);

/*CRIANDO UM TABELA QUE VAI SE RELACIONAR COM A TABELA CATEGORIA*/

CREATE TABLE IF NOT EXISTS PRODUTOS( ID_PRODUTOS INT PRIMARY KEY AUTO_INCREMENT,
  DESCRICAO TEXT NOT NULL,PRECO FLOAT NOT NULL,
  /*UTILIZANDO CHAVE ESTRANGEIRA*/
  CATEGORIA_ID INT NOT NULL, FOREIGN KEY(CATEGORIA_ID) REFERENCES CATEGORIAS(ID_CATEGORIAS));

/*
INSERIDNO DADOS NA PRIMEIRA TABELA*/
MariaDB [BANCOTREINAMENTO]> INSERT INTO CATEGORIAS VALUE(DEFAULT,'FRIOS');

/*INSERINDO DADOS NA SEGUNDA TABELA*/
MariaDB [BANCOTREINAMENTO]> INSERT INTO PRODUTOS(ID_PRODUTOS,DESCRICAO,PRECO,CATEGORIA_ID) VALUES(DEFAULT, 'PRIMEIRO PRODUTO',25.00,1); /*1 FAZ REFERENCIA AO PRIMEIRO ID DO ITEM DA TABELA PRODUTO*/
